package com.betterfly.domain.enumeration;

/**
 * The Rubrique enumeration.
 */
public enum Rubrique {
    RUBRIQUE,
    NETTOYAGE,
    EVACUATION_EAUX,
    SANITAIRES,
    REFECTOIRES_HEBERGEMENT,
    DISPOSITIONS_DIVERSES,
    AMENAGEMENT_LOCAUX,
    AMBIANCES,
    ORGANISATION_RH,
    CHS,
    CONVENTION119,
    PROTECTION_MACHINES,
    DISPOSITIFS_PROTECTION,
    CONFORMITE,
    APPAREILS_LEVAGE,
    CABINES_MOYENS_ACCES,
    INSTALLATIONS_ELECTRIQUES,
    ECLAIRAGE_SECOURS,
    CABINE_PEINTURE_PULVIRISEE,
    AT,
    PRODUIT_CHIMIQUES,
    SERVICE_MEDICAL,
    DISPOSITIONS_COMMUNES,
    PREVENTION_CONTRE_INCENDIE,
    COVID,
    ENVIRONNEMENT,
    CODE_TRAVAIL,
}
