export enum Rubrique {
  RUBRIQUE = 'RUBRIQUE',

  NETTOYAGE = 'NETTOYAGE',

  EVACUATION_EAUX = 'EVACUATION_EAUX',

  SANITAIRES = 'SANITAIRES',

  REFECTOIRES_HEBERGEMENT = 'REFECTOIRES_HEBERGEMENT',

  DISPOSITIONS_DIVERSES = 'DISPOSITIONS_DIVERSES',

  AMENAGEMENT_LOCAUX = 'AMENAGEMENT_LOCAUX',

  AMBIANCES = 'AMBIANCES',

  ORGANISATION_RH = 'ORGANISATION_RH',

  CHS = 'CHS',

  CONVENTION119 = 'CONVENTION119',

  PROTECTION_MACHINES = 'PROTECTION_MACHINES',

  DISPOSITIFS_PROTECTION = 'DISPOSITIFS_PROTECTION',

  CONFORMITE = 'CONFORMITE',

  APPAREILS_LEVAGE = 'APPAREILS_LEVAGE',

  CABINES_MOYENS_ACCES = 'CABINES_MOYENS_ACCES',

  INSTALLATIONS_ELECTRIQUES = 'INSTALLATIONS_ELECTRIQUES',

  ECLAIRAGE_SECOURS = 'ECLAIRAGE_SECOURS',

  CABINE_PEINTURE_PULVIRISEE = 'CABINE_PEINTURE_PULVIRISEE',

  AT = 'AT',

  PRODUIT_CHIMIQUES = 'PRODUIT_CHIMIQUES',

  SERVICE_MEDICAL = 'SERVICE_MEDICAL',

  DISPOSITIONS_COMMUNES = 'DISPOSITIONS_COMMUNES',

  PREVENTION_CONTRE_INCENDIE = 'PREVENTION_CONTRE_INCENDIE',

  COVID = 'COVID',

  ENVIRONNEMENT = 'ENVIRONNEMENT',

  CODE_TRAVAIL = 'CODE_TRAVAIL',
}
